spring:
  application:
    name: demo-authorization
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/commerce

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081



